{
  "formatVersion": "1.1",
  "component": {
    "group": "com.whereby",
    "module": "sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0.aar",
          "url": "sdk-0.1.0.aar",
          "size": 19420,
          "sha512": "4e6173385e576f4f620bf414b6c24f779fdc7bf3c09b32fac94c2fd7f50fd16f42265d6769d04e1ed0ce59d7589822cb02e24667367c59a16e89cca187f07c04",
          "sha256": "b998d63a59060521dacada92da45e124f00d25524854f018084be2f513ae464e",
          "sha1": "6b7e411e6d9d5a57b85c01548dc32114c7a76503",
          "md5": "7b7347f425d3a67ebb4e35c6d46d05c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.1.0.aar",
          "url": "sdk-0.1.0.aar",
          "size": 19420,
          "sha512": "4e6173385e576f4f620bf414b6c24f779fdc7bf3c09b32fac94c2fd7f50fd16f42265d6769d04e1ed0ce59d7589822cb02e24667367c59a16e89cca187f07c04",
          "sha256": "b998d63a59060521dacada92da45e124f00d25524854f018084be2f513ae464e",
          "sha1": "6b7e411e6d9d5a57b85c01548dc32114c7a76503",
          "md5": "7b7347f425d3a67ebb4e35c6d46d05c4"
        }
      ]
    }
  ]
}
